### ISSUE TITLE
Possible to set all fields as no create and no create/edit?

### ISSUE THREAD

**Issue by samigosms** [0k/web_m2o_enhanced#5]
Hello. I have an instance where I will never need the user to create or create/edit any field they do not have write/create access. Is it possible to shut down these options for all fields without having to go into the form view and do it manually for everything?

Also, does this module support splitting in serial numbers? I have tested it and I think I may be doing something wrong. I have enabled the module and added the options in the view for splitting serial numbers as well as removed access rights to create/write for myself. When I go into delivery orders and split in a serial number, the options to create and create/edit are still there. I just need this gone and it's the only blocker I have for launching OpenERP so I've been working around the clock to get it to work.

Do you have an example of how I would get this working with the split serial numbers for the warehouse workers? I have to have them all able to add the serial numbers, just not create any new ones.

Thanks for your help.

**Comment by njeudy** [comment]
Hello,

For many2one field write/create access are managed (but not for many2many).
So if one user as no write or create access to the model, you should'nt not
see these options.

For splitting in serial number I will test it because normaly there is no
issue on any field .. I will give it a try.

We update this module and include in in community modules: you can find it
here : https://www.openerp.com/apps/7.0/web_m2x_options/
Github project will be updated soon.

Nicolas JEUDY

Expert Technique et Fonctionnel Système d'Information
TUXSERVICES

22 rue du seminaire - 25170 Pelousey
e-mail : njeudy@tuxservices.com
mob. : +33 (0)6 28 95 36 64
http://www.tuxservices.com

2014/1/13 RKS213 notifications@github.com

**Comment by njeudy** [comment]
You can use 0k/web_m2x_options new project and this support global config:

Now you can disable "Create..." and "Create and Edit..." entry for all fields in the odoo instance. If you disable one option, you can enable it for particular field by setting "create: True" option directly on the field definition.

web_m2x_options.create boolean (Default: depends if user have create rights)

Whether to display the "Create..." entry in dropdown panel for all fields in the odoo instance.
web_m2x_options.create_edit boolean (Default: depends if user have create rights)

Whether to display "Create and Edit..." entry in dropdown panel for all fields in the odoo instance.
web_m2x_options.limit int (Default: openerp default value is 7)

Number of displayed record in drop-down panel for all fields in the odoo instance
To add these parameters go to Configuration -> Technical -> Parameters -> System Parameters and add new parameters like:

web_m2x_options.create: False
web_m2x_options.create_edit: False
web_m2x_options.limit: 10
